### ISSUE TITLE
Category selection popup shows all categories instead of showing only allowed category

### ISSUE THREAD

**Issue by GauravBhatiaBain** [Geta/EpiCategories#31] opened 2020-04-22 06:24 UTC
We are using Geta.EpiCategories package in our code and utilizing it on the property for category selection like shown below.
     [CultureSpecific]
        [Display(
            Name = "Industries",
            Order = 510,
            GroupName = CustomTabNames.Taxonomy)]
        **[Categories]
        [AllowedTypes(new[] { typeof(IndustryCategory) })]**
        public virtual IEnumerable<ContentReference> Industries { get; set; }

When we were on 1.2.6 version, we were getting only allowed categories(see below pic) in the selection like Industry Category
![image](https://user-images.githubusercontent.com/11024330/79947634-e8413a00-848f-11ea-8db3-b783f4c4d653.png)

but now, we have upgraded the package from **1.2.6 to 1.2.10** and the Category selection popup(see below pic) is now showing all category types in the latest version, instead of showing just allowed category type like shown in the above pic.
![image](https://user-images.githubusercontent.com/11024330/79947586-d2cc1000-848f-11ea-85c4-484b51ab6029.png)

 

Question: Is there a way to show only Allowed category type in the selection popup and hide the other category types?

**Comment by MattisOlsson** [comment] 2020-05-12 06:44
Hi!

This is weird since nothing regarding this has been changed between these versions. I will take a look at this. Did you also upgrade Episerver in relation to this?

**Comment by MattisOlsson** [comment] 2020-05-12 06:51
Hello again.

Are you sure this has worked in earlier versions? This is the code in the CategoriesAttribute:

https://github.com/Geta/EpiCategories/blob/master/src/EpiCategories/DataAnnotations/CategoriesAttribute.cs#L36

However, I will add support for the AllowedTypesAttribute and create a new release. I'll let you know when it's published.

**Comment by GauravBhatiaBain** [comment] 2020-05-12 06:56
@MattisOlsson Yes, it worked with the earlier version. 
We upgraded the following packages:
Episerver.CMS from 11.12.0 to 11.15.0
Episerver.CMS.UI from 11.23.0 to 11.24.0

**Comment by MattisOlsson** [comment] 2020-05-12 08:12
I can't reproduce this. Just to make things clear: The category selector shows all category types, but only the AllowedTypes are selectable (with a checkbox to left of the label), provided that the "IsSelectable" property is set to true. This is the way default Episerver selectors work as well. They show everything, but you can only select the allowed types. Because it might be possible to have an allowed category nested somewhere.

I don't see any checkbox at all in your screenshots, are you sure you can select any of them? :)

I will investigate if I can easily add a css class to those nodes so they are a bit grayed out (disabled).

**Comment by GauravBhatiaBain** [comment] 2020-05-12 08:54
The category selector shows all category types and provides checkbox only for the allowed types, not for the other types. 

But for the better user experience, Is it possible to show only allowed category types & hide the other categories from the category selection popup? 
Instead of adding a class to grey out, can you add Hide class to hide the disabled categories from the selection?

**Comment by MattisOlsson** [comment] 2020-05-12 09:07
I can't imagine how it could ever have worked like you say in 1.2.6, maybe because of differences in Episerver perhaps, since this has not been changed in the package.

Unfortunately, I don't want to hide disabled categories because there might be children to those categories which are actually allowed.

**Comment by MattisOlsson** [comment] 2020-05-12 09:15
Oh, I see it has been changed. But previously, it wasn't possible to select sub categories (even though they are allowed) if the categories on the first level was always hidden because they were not matching allowed types.

I might add a setting for this in the future, but default will always be like it currently is.

**Comment by MattisOlsson** [comment] 2020-05-12 09:57
It turned out to be an easy fix so I added this setting. See updated README for details. I just uploaded version 1.2.11 to the Episerver feed so it will be available in the next few days. Closing this issue now.

**Closed by MattisOlsson** 2020-05-12 09:57 UTC

**Comment by GauravBhatiaBain** [comment] 2020-05-12 10:08
Wow! that was quick. Thanks for the fix @MattisOlsson
