### ISSUE TITLE
Episerver version compare not working after install

### ISSUE THREAD

**Issue by mikefitt** [Geta/EpiCategories#8] opened 2018-06-14 14:57 UTC
I've noticed that the version "compare" view in edit mode is no longer working for pages where I have a populated property that is decorated with the [Categories] attribute (instead of showing the all properties view with changes highlighted it just shows a preview of the page).

**Comment by MattisOlsson** [comment] 2018-06-15 07:37
Ok, I'll test it a bit and report back.

**Comment by MattisOlsson** [comment] 2018-06-19 11:19
You are right, I confirmed it. Really strange. I have to try to figure out how to solve this.

**Comment by MattisOlsson** [comment] 2018-06-19 12:07
I found the cause and it is now fixed. The store property in the CategorySelector dojo widget was initialized at postCreate and it was apparently too late for compare view so I moved initialization to postMixInProperties instead. I just uploaded version 1.2.4 to Episerver NuGet feed so please check for updates in the next few days.

**Closed by MattisOlsson** 2018-06-19 12:07 UTC

**Comment by MattisOlsson** [comment] 2018-06-19 12:12
If you want to quick fix this, just update CategorySelector javascript in ~/modules/_protected/geta-epicategory/ClientResources/Scripts/widget. You can replace it with attached file.
[CategorySelector.zip](https://github.com/Geta/EpiCategories/files/2115089/CategorySelector.zip)

**Comment by mikefitt** [comment] 2018-06-19 14:43
That's great - thanks for taking time to look at this.  I'm working off version 10 of Episerver so I'll take a look at implementing the fix you mentioned.

**Comment by MattisOlsson** [comment] 2018-06-19 14:45
Ok, the only thing that's needed is renaming postCreate method to postMixInProperties (be careful with case sensitivity).
